[build]
  command = "cp client/src/main.vercel.tsx client/src/main.tsx && cp client/src/index.vercel.css client/src/index.css && cd client && vite build --config vite.config.vercel.js"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200